### PR TITLE
WIP: Begin work on block-inputs

### PR DESCRIPTION
**Pull request by johnmcclumpha**
So I started playing with implementing the "block inputs" which will form part of Mercury (alongside other inputs) but wanted to run some ideas and thoughts past you both @kevinleedrum, @mitcsutt and @Nineswiss 

When used in a form with multiple inputs, these will display in a "grid" of sorts

The changes in this PR are an initial attempt to introduce a "block" attribute on the existing inputs to display these in the revised styling, however this raises some concerns:

1. we're using weird CSS hacks to change the order things are displayed (not reflecting the structure in the DOM) - eg assistive text
2. We can't simply place these into a container that easily accommodates them without some hackery to remove double borders etc
3. There's a LOT of conditional logic being added to render these and I'd imagine in a huge page full of them that it'd slow down paint times considerably

I'm leaning more towards creating separate "block inputs" (mx-block-input, mx-block-select, mx-block-textarea, etc) which would still have a compatible interface but would remove the crazy amounts of conditional logic required for rendering and styling. It would also mean we could do some really great tricks to get borders working nicely with (potentially) some parent "block" helpers. We could also utilise a container component or similar to contain the different input types to reduce the wetness of the codebase. Thoughts?

Example designs below:

image

image

### CODE REVIEW

**Comment by kevinleedrum** [comment]
I definitely think some sort of parent component would be helpful, especially to achieve things like border collapsing and responsive/adaptive patterns.

The extra logic for this one component to accommodate the `block` prop isn't too bad, but once you add in the selects, textareas, checkbox groups, etc. I think it does make more sense to create a family of "block" components.

I also just realized we should probably have an `aria-describedby` attribute on the input that references the assistive text element.  That would make the DOM order somewhat less of an issue.

**Comment by mitcsutt** [comment]
I agree with all said above. Parent component makes sense, and individual child components. Because more will need to be added which makes the conditions even more varied.

I wonder about the best method to define layouts. Is it the parents responsibility to receive a prop and define (e.g. `layout={[['25%', '25%', '50%'], ['50%', '50%']]|`. Or the responsibility of each child (e.g. `width="25%`)?

**Comment by johnmcclumpha** [comment]
> I wonder about the best method to define layouts.

I'm keen to look at utilising the existing tailwind grid stuff but will need to dig into things a bit more to see how they're putting it all together

**Comment by johnmcclumpha** [comment]
@mitcsutt @kevinleedrum - I'm closing this in favour of: https://github.com/moxiworks/mds/pull/274

**Pull request closed without merging**
